spring.application.name=loanflow

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=loanflow;encrypt=false;trustServerCertificate=true
spring.datasource.username=loanflow_user
spring.datasource.password=Loanflow@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

loanflow.jwt.secret=${JWT_SECRET:loanflow-dev-secret-change-me-loanflow-dev-secret-change-me}
loanflow.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:120}
loanflow.contract.storage-path=${CONTRACT_STORAGE_PATH:contracts}
