package com.api.loanflow.contrato.dominio;

public enum EventoAssinaturaTipo {
	DESAFIO_INICIADO,
	DESAFIO_VALIDADO,
	DESAFIO_CONSUMIDO,
	ASSINATURA_RECUSADA,
	DESAFIO_EXPIRADO,
	ASSINATURA_CONFIRMADA,
	CONTRATO_EXPIRADO,
	CONTRATO_FORMALIZADO
}
